name: Release

on:
  release:
    types: [ created ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build with Gradle
        run: ./gradlew assemble

      - name: Run tests
        run: ./gradlew test

      - name: Decode GPG key
        run: |
          echo "${{ secrets.SIGNING_KEY }}" > signing-key.gpg
          gpg --quiet --batch --yes --import signing-key.gpg
          rm signing-key.gpg

      - name: Publish to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publish --no-configuration-cache

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: lib/build/libs/*.jar
          generate_release_notes: true
          append_body: true
          make_latest: true
          token: ${{ secrets.GITHUB_TOKEN }}
